global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules from files in the rules directory
rule_files:
  - "/etc/prometheus/rules/alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # RealStack API
  - job_name: 'realstack-api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:3000']
        labels:
          service: 'api'
          environment: 'production'

  # RealStack Frontend
  - job_name: 'realstack-frontend'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['frontend:3001']
        labels:
          service: 'frontend'
          environment: 'production'

  # Blockchain Exporter
  - job_name: 'blockchain-exporter'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['blockchain-exporter:9101']
        labels:
          service: 'blockchain'
          environment: 'production'

  # Additional RealStack Services
  - job_name: 'realstack-services'
    metrics_path: '/metrics'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - '/etc/prometheus/services/*.json'
        refresh_interval: 5m
      
  # Dynamic service discovery for additional services
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name 