FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application code
COPY . .

# Expose port for the application
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "start"] 