name: Deploy

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd apps/frontend
          npm ci || npm install
      
      - name: Build frontend
        run: |
          cd apps/frontend
          npm run build
      
      - name: Deploy to production
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "Deploying version $(git describe --tags) to production"
          # Deployment steps would go here
        
      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to staging environment"
          # Staging deployment steps would go here

  deploy-development:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install Dependencies
      run: |
        cd apps/frontend
        npm ci
        cd ../backend
        npm ci
    
    - name: Build Frontend
      run: |
        cd apps/frontend
        npm run build
    
    - name: Build Backend
      run: |
        cd apps/backend
        npm run build
    
    - name: Deploy to Development
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SERVER_USERNAME }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        script: |
          cd /var/www/realstack-dev
          git pull
          cd apps/frontend
          npm ci
          npm run build
          cd ../backend
          npm ci
          npm run build
          pm2 restart realstack-dev-backend
  
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install Dependencies
      run: |
        cd apps/frontend
        npm ci
        cd ../backend
        npm ci
    
    - name: Build Frontend
      run: |
        cd apps/frontend
        npm run build
    
    - name: Build Backend
      run: |
        cd apps/backend
        npm run build
    
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_HOST }}
        username: ${{ secrets.PROD_SERVER_USERNAME }}
        key: ${{ secrets.PROD_SERVER_SSH_KEY }}
        script: |
          cd /var/www/realstack
          git pull
          cd apps/frontend
          npm ci
          npm run build
          cd ../backend
          npm ci
          npm run build
          pm2 restart realstack-backend

  deploy-contract:
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Solana
      uses: ./.github/actions/setup-solana
      with:
        solana-version: '1.16.0'
    
    - name: Set up Anchor
      run: |
        npm install -g @project-serum/anchor-cli@0.27.0
    
    - name: Build Contract
      run: |
        cd contracts
        anchor build
    
    - name: Deploy Contract (Only if changes)
      run: |
        cd contracts
        # Check if there are changes that require deployment
        if [[ $(git diff --name-only HEAD~1 HEAD | grep -c "contracts/") -gt 0 ]]; then
          anchor deploy --provider.cluster mainnet --provider.wallet ~/.config/solana/id.json
        else
          echo "No contract changes detected, skipping deployment"
        fi
      env:
        ANCHOR_WALLET: ${{ secrets.ANCHOR_WALLET }} 